In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import datetime as dt

In [11]:
#import csv
hollywood = pd.read_csv('Hollywood.csv', encoding = "latin")
hollywood.head()

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
0,1,tt0316654,2012-12-21,2012-12-21,NaN,Spider-Man 2,https://www.imdb.com/title/tt0316654/,movie,7.3,127.0,2004,"Action, Adventure, Sci-Fi",537324,2004-06-25,Sam Raimi,10.0,2016-08-15
1,2,tt0317919,2012-12-21,2012-12-21,NaN,Mission: Impossible III,https://www.imdb.com/title/tt0317919/,movie,6.9,126.0,2006,"Action, Adventure, Thriller",326934,2006-04-24,J.J. Abrams,10.0,2016-08-15
2,3,tt0942385,2012-12-21,2012-12-21,NaN,Tropic Thunder,https://www.imdb.com/title/tt0942385/,movie,7.0,107.0,2008,"Action, Comedy, War",374288,2008-08-11,Ben Stiller,10.0,2016-08-15
3,4,tt0407887,2012-12-21,2012-12-21,NaN,The Departed,https://www.imdb.com/title/tt0407887/,movie,8.5,151.0,2006,"Crime, Drama, Thriller",1172148,2006-09-26,Martin Scorsese,10.0,2016-08-15
4,5,tt0145487,2012-12-21,2012-12-21,NaN,Spider-Man,https://www.imdb.com/title/tt0145487/,movie,7.3,121.0,2002,"Action, Adventure, Sci-Fi",680573,2002-04-30,Sam Raimi,10.0,2016-08-15

In [12]:
#import 
bollywood = pd.read_csv('Bollywood.csv', encoding = "latin")
bollywood.head()

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
0,2,tt0420332,2012-12-21,2012-12-21,NaN,Veer-Zaara,https://www.imdb.com/title/tt0420332/,movie,7.8,192,2004,"Drama, Family, Musical, Romance",48342,2004-11-12,Yash Chopra,10.0,2012-12-24
1,3,tt0347473,2012-12-21,2012-12-21,NaN,Main Hoon Na,https://www.imdb.com/title/tt0347473/,movie,7.0,182,2004,"Action, Comedy, Drama, Musical, Romance, Thriller",31844,2004-04-30,Farah Khan,10.0,2019-08-03
2,4,tt0213890,2012-12-21,2012-12-21,NaN,Mohabbatein,https://www.imdb.com/title/tt0213890/,movie,7.1,216,2000,"Musical, Drama, Romance",26885,2000-10-27,Aditya Chopra,10.0,2019-08-03
3,5,tt0126871,2012-12-21,2012-12-21,NaN,Deewana,https://www.imdb.com/title/tt0126871/,movie,6.9,185,1992,"Action, Comedy, Crime, Musical, Romance",6039,1992-06-25,Raj Kanwar,NaN,NaN
4,6,tt0110222,2012-12-21,2012-12-21,NaN,Kabhi Haan Kabhi Naa,https://www.imdb.com/title/tt0110222/,movie,7.8,158,1994,"Comedy, Drama, Music, Musical, Romance",17103,1994-02-25,Kundan Shah,NaN,NaN

In [13]:
#combine dataframes
movies_df = pd.concat([hollywood, bollywood], ignore_index=True)
movies_df

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
0,1,tt0316654,2012-12-21,2012-12-21,NaN,Spider-Man 2,https://www.imdb.com/title/tt0316654/,movie,7.3,127.0,2004,"Action, Adventure, Sci-Fi",537324,2004-06-25,Sam Raimi,10.0,2016-08-15
1,2,tt0317919,2012-12-21,2012-12-21,NaN,Mission: Impossible III,https://www.imdb.com/title/tt0317919/,movie,6.9,126.0,2006,"Action, Adventure, Thriller",326934,2006-04-24,J.J. Abrams,10.0,2016-08-15
2,3,tt0942385,2012-12-21,2012-12-21,NaN,Tropic Thunder,https://www.imdb.com/title/tt0942385/,movie,7.0,107.0,2008,"Action, Comedy, War",374288,2008-08-11,Ben Stiller,10.0,2016-08-15
3,4,tt0407887,2012-12-21,2012-12-21,NaN,The Departed,https://www.imdb.com/title/tt0407887/,movie,8.5,151.0,2006,"Crime, Drama, Thriller",1172148,2006-09-26,Martin Scorsese,10.0,2016-08-15
4,5,tt0145487,2012-12-21,2012-12-21,NaN,Spider-Man,https://www.imdb.com/title/tt0145487/,movie,7.3,121.0,2002,"Action, Adventure, Sci-Fi",680573,2002-04-30,Sam Raimi,10.0,2016-08-15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2777,193,tt0457940,2019-10-12,2019-10-12,NaN,Home Delivery: Aapko... Ghar Tak,https://www.imdb.com/title/tt0457940/,movie,3.1,151.0,2005,"Comedy, Romance",584,2005-12-02,Sujoy Ghosh,NaN,NaN
2778,194,tt7430722,2019-12-01,2019-12-01,NaN,War,https://www.imdb.com/title/tt7430722/,movie,6.5,154.0,2019,"Action, Thriller",18645,2019-10-02,Siddharth Anand,NaN,NaN
2779,195,tt0173102,2019-12-27,2019-12-27,NaN,Raju Ban Gaya Gentleman,https://www.imdb.com/title/tt0173102/,movie,6.8,152.0,1992,"Musical, Comedy, Romance",7123,1992-11-13,Aziz Mirza,NaN,NaN
2780,196,tt8504014,2020-03-08,2020-03-08,NaN,Good Newwz,https://www.imdb.com/title/tt8504014/,movie,7.0,134.0,2019,Comedy,13686,2019-12-27,Raj Mehta,NaN,NaN
2781,197,tt9248952,2020-03-29,2020-03-29,NaN,Jawaani Jaaneman,https://www.imdb.com/title/tt9248952/,movie,6.7,119.0,2020,Comedy,5630,2020-01-31,Nitin Kakkar,NaN,NaN